置底nav：基本資料 日誌 （按鈕-照相機-即時分析） 產品管理  AI營養師


首頁：基本資料
----------------------------------
        
               

              寵物照片


                          
                          寵物名
 -------------------------------
 比熊犬  公
 9.2公斤 10歲
 ----------------------------
 #淚腺 ＃腸胃敏感 ＃牙結石
 ----------------------------
 #每日大便2次 偏軟
 #尿正常 ＃本州外出3次 ＃每日運動 
 #精神好
 ----------------------------
 健康狀況
 
 圓圈一     圓圈二      圓圈三

 ----------------------------
 營養素總表
 
 營養素量總和分析表

 AI解析   推薦營養素   風險整理

 （按鈕-重新解析）

 ----------------------------
 使用產品 （固定＋試用）

 飼料：

 保健品：

 潔牙品：

 其他：

----------------------------------

日誌
----------------------------------


            月曆（大格）
            今日格子底色不同


 --------------------------------
            （按鈕-紀錄）
 當日日期
 心得筆記內容

----------------------------------

日誌 > 單日心得編輯頁面
----------------------------------
X            當月份
（選取日期的當週 周曆）
寫日記(卡片顯示)
  #試用產品 ＃固定產品 ＋新增其他標籤
 ------------------------------
 | 新增紀錄......               |
 |                             |
 ------------------------------
 外出(卡片顯示)

 ------------------------------
 運動(卡片顯示)

 ------------------------------
 尿(卡片顯示)
 （按鈕-正常）   （按鈕-不正常）
 顏色
 （顏色選擇）
 ------------------------------
 排便(卡片顯示)
 每日  次。 

 便便
 軟---------(托拉選擇)-----硬
 1                       10
 ------------------------------
 喝水
 少   正常   多
 ------------------------------
 產品使用方式(卡片顯示)
 早

 中

 晚

 ------------------------------

----------------------------------

 (按鈕-照相機-即時分析)
----------------------------------
即時分析紀錄           （按鈕-新增分析）

分析紀錄
 第一筆紀錄 （卡片顯示）
 第二筆紀錄 （卡片顯示）

----------------------------------

即時分析-新增分析 （彈窗顯示）
----------------------------------
 -------------------------------
 |                             |
 |                             |
 |           相機圖案           |
 |                             |
 |                             |
 -------------------------------
    （按鈕-拍照） （按鈕-上傳圖片）

        （按鈕-ai 即時分析）
----------------------------------

產品管理
----------------------------------
 頁籤-固定清單   頁籤-試用清單
 --------------------------------
  產品1. 產品名稱 （卡片顯示）
  使用狀況紀錄             
                         AI解析 
  -----------------------------                        
  產品1. 產品名稱 （卡片顯示）
  使用狀況紀錄             
                         AI解析 
  -----------------------------        
 --------------------------------
         （按鈕-＋新增產品）

----------------------------------

產品管理 > 新增固定產品（彈窗顯示）
----------------------------------
 新增固定產品                     Ｘ
 --------------------------------
 | 搜尋產品名稱或品牌              |
 -------------------------------- 
  產品1 產品名稱（卡片顯示）  刪除
  產品2 產品名稱（卡片顯示）  刪除
  產品3 產品名稱（卡片顯示）  刪除  

      （按鈕-ＡＩ推薦產品）         

----------------------------------

產品管理 > 新增試用產品（彈窗顯示）
----------------------------------
 新增試用產品                     Ｘ
 --------------------------------
 | 搜尋產品名稱或品牌              |
 -------------------------------- 
  產品1 產品名稱（卡片顯示）  刪除
  產品2 產品名稱（卡片顯示）  刪除
  產品3 產品名稱（卡片顯示）  刪除  

      （按鈕-ＡＩ推薦產品）         

----------------------------------

AI營養師
----------------------------------
 --------------------------------
 |                              |
 |                              |
 |                              |
 |                              |
 |                              |
 |          對話紀錄。            |
 |                              |
 |                              |
 |                              |
 |                              |
 |                              |
 |                              |
 |                              |
 --------------------------------
 --------------------------------
 |  請輸入內容。            |  >  |
 --------------------------------
----------------------------------